# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 07:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО врача')),
            ],
            options={
                'verbose_name': 'ФИО врача',
                'verbose_name_plural': 'ФИО врачей',
            },
        ),
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Запрещенное слово')),
            ],
            options={
                'verbose_name': 'Запрещенное слово',
                'verbose_name_plural': 'Запрещенные слова',
            },
        ),
        migrations.CreateModel(
            name='PermittedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово-исключение')),
            ],
            options={
                'verbose_name': 'Слово-исключение',
                'verbose_name_plural': 'Слова-исключения',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания отзыва')),
                ('dt_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время редактирования отзыва')),
                ('origin_text', models.TextField(verbose_name='Исходный отзыв')),
                ('finished_text', models.TextField(verbose_name='Обработанный отзыв')),
                ('moderation_flag', models.BooleanField(default=False, verbose_name='Отзыв отмодерирован')),
                ('user_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Doctor', verbose_name='ФИО врача')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, оставивший отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(to='main.Specialty'),
        ),
    ]
