# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191127_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermittedWords',
            new_name='PermittedWord',
        ),
    ]
