# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191127_1046'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['id', 'fio'], name='main_doctor_id_c770cc_idx'),
        ),
    ]
