# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-29 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191127_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['fio'], 'verbose_name': 'ФИО врача', 'verbose_name_plural': 'ФИО врачей'},
        ),
    ]
